version: '2'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  bot:
    build: src
    image: shortcuts_bot
    restart: always
    dns:
      - 8.8.8.8
    env_file:
      - .env
    ports:
      - '127.0.0.1:${CONTAINER_PORT}:8000'
